
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Entry entry3;
	private global::Gtk.Entry entry2;
	private global::Gtk.Button button1;
	private global::Gtk.VBox vbox3;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Entry entry6;
	private global::Gtk.Entry entry7;
	private global::Gtk.Button button3;
	private global::Gtk.Label label5;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label6;
	private global::Gtk.Label label7;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Entry entry4;
	private global::Gtk.Entry entry5;
	private global::Gtk.Button button2;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Label label8;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.hbox3.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.HeightRequest = 20;
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1             y        numero 2");
		this.vbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.hbox1.Add (this.entry3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry3]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.hbox1.Add (this.entry2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry2]));
		w5.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		// Container child button1.Gtk.Container+ContainerChild
		global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w7 = new global::Gtk.HBox ();
		w7.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w8 = new global::Gtk.Image ();
		w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		w7.Add (w8);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w10 = new global::Gtk.Label ();
		w10.LabelProp = global::Mono.Unix.Catalog.GetString ("Sumar");
		w10.UseUnderline = true;
		w7.Add (w10);
		w6.Add (w7);
		this.button1.Add (w6);
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.WidthRequest = 190;
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.hbox2.Add (this.label3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.WidthRequest = 190;
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.hbox2.Add (this.label4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entry6 = new global::Gtk.Entry ();
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '•';
		this.hbox4.Add (this.entry6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entry6]));
		w19.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entry7 = new global::Gtk.Entry ();
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '•';
		this.hbox4.Add (this.entry7);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entry7]));
		w20.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		// Container child button3.Gtk.Container+ContainerChild
		global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w22 = new global::Gtk.HBox ();
		w22.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w23 = new global::Gtk.Image ();
		w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-stop", global::Gtk.IconSize.Menu);
		w22.Add (w23);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w25 = new global::Gtk.Label ();
		w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Resta");
		w25.UseUnderline = true;
		w22.Add (w25);
		w21.Add (w22);
		this.button3.Add (w21);
		this.hbox4.Add (this.button3);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button3]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.vbox4.Add (this.label5);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label5]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.WidthRequest = 190;
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1:");
		this.hbox5.Add (this.label6);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label6]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.WidthRequest = 190;
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2:");
		this.hbox5.Add (this.label7);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label7]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
		w34.Position = 3;
		w34.Expand = false;
		w34.Fill = false;
		this.vbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '•';
		this.hbox6.Add (this.entry4);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entry4]));
		w36.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry ();
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '•';
		this.hbox6.Add (this.entry5);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entry5]));
		w37.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		// Container child button2.Gtk.Container+ContainerChild
		global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w39 = new global::Gtk.HBox ();
		w39.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w40 = new global::Gtk.Image ();
		w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-stop", global::Gtk.IconSize.Menu);
		w39.Add (w40);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w42 = new global::Gtk.Label ();
		w42.LabelProp = global::Mono.Unix.Catalog.GetString ("Multiplicar");
		w42.UseUnderline = true;
		w39.Add (w42);
		w38.Add (w39);
		this.button2.Add (w38);
		this.hbox6.Add (this.button2);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button2]));
		w46.Position = 2;
		w46.Expand = false;
		w46.Fill = false;
		this.vbox3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
		w47.Position = 1;
		w47.Expand = false;
		w47.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.vbox5.Add (this.label8);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label8]));
		w48.Position = 0;
		w48.Expand = false;
		w48.Fill = false;
		this.vbox3.Add (this.vbox5);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
		w49.Position = 2;
		this.vbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
		w50.Position = 3;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 435;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
